version: '3'

volumes:
  calender_api_local_postgres_data: {}
  calender_api_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: calender_api_local_django
    container_name: calender_api_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.tokens
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: calender_api_production_postgres
    container_name: calender_api_local_postgres
    volumes:
      - calender_api_local_postgres_data:/var/lib/postgresql/data
      - calender_api_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres