# Generated by Django 4.0.10 on 2023-02-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googletokens',
            name='email',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
