# Generated by Django 4.0.10 on 2023-02-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_googletokens_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='googletokens',
            name='ip',
            field=models.CharField(default='none', max_length=225),
            preserve_default=False,
        ),
    ]
